apiVersion: v1
kind: Service
metadata:
  name: maven-service
spec:
  type: NodePort
  ports:
  - name: maven
    port: 8080
    nodePort: 31002
    targetPort: 8080
    protocol: TCP
  selector:
    app: k8s-first-test
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maven-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-first-test
    spec:
      containers:
        - name: maven
          image: 47.102.122.97:5000/k8s-first-test:latest
          ports:
          - containerPort: 8080
          env:
            - name: key
              value: "value"
